// Code generated by "stringer -type=ColType"; DO NOT EDIT

package dataframe

import "fmt"

const _ColType_name = "ColTypeUnknownColTypeBoolColTypeIntColTypeFloatColTypeStringColTypeMaxVal"

var _ColType_index = [...]uint8{0, 14, 25, 35, 47, 60, 73}

func (i ColType) String() string {
	if i >= ColType(len(_ColType_index)-1) {
		return fmt.Sprintf("ColType(%d)", i)
	}
	return _ColType_name[_ColType_index[i]:_ColType_index[i+1]]
}
